# Generated by Django 4.0.2 on 2022-02-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_alter_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='creation_date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
