# Generated by Django 4.0.2 on 2022-02-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_post_image_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='notfound.jpg', null=True, upload_to='uploads/'),
        ),
    ]
