# Generated by Django 4.0.2 on 2022-02-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='uploads/notfound.jpg', null=True, upload_to='uploads/'),
        ),
    ]
