# Generated by Django 4.0.2 on 2022-02-23 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_alter_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('roll', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MultiTableParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colg', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProxyParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('roll', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MultiTableChild',
            fields=[
                ('multitableparent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog_app.multitableparent')),
                ('name', models.CharField(max_length=50)),
                ('roll', models.CharField(max_length=10)),
            ],
            bases=('blog_app.multitableparent',),
        ),
        migrations.CreateModel(
            name='ProxyChild',
            fields=[
            ],
            options={
                'ordering': ['-roll'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('blog_app.proxyparent',),
        ),
    ]
