# Generated by Django 4.0.2 on 2022-02-23 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_abstractchild_multitableparent_proxyparent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proxychild',
            options={'ordering': ['-name']},
        ),
    ]
