# Generated by Django 4.0.2 on 2022-02-24 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_alter_proxychild_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyPost',
            fields=[
            ],
            options={
                'verbose_name': 'ProxyPost',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('blog_app.post',),
        ),
    ]
