# Generated by Django 4.0.2 on 2022-02-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0009_proxypost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Singleton',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Singleton',
                'verbose_name_plural': 'Singletons',
            },
        ),
    ]
