# Generated by Django 4.0.2 on 2022-02-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0010_singleton'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singleton',
            name='key',
        ),
        migrations.AddField(
            model_name='singleton',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
