# Generated by Django 4.0.2 on 2022-02-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0011_remove_singleton_key_singleton_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlankTrueModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NullTrueModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, null=True)),
            ],
        ),
    ]
